easy-graph/Easy-Graph

- .gitignore
- easygraph/classes/directed_graph.py
- easygraph/functions/__init__.py
- easygraph/functions/centrality/__init__.py
- easygraph/functions/centrality/centrality.py
- easygraph/functions/community/modularity_max_detection.py
- easygraph/functions/path/path.py
Modifying some detail includes：
in path.py:
1. replace ["weight"] with .get("weight",1)
2. add : k=node to avoid "local variable 'k' referenced before assignment"
in directed_graph.py:
1. I remain "return self._node" cause i guess if one person want to access the nodes, he/she may also want to access the "node_attr" except the node.
in greedy_modularity_communities.py:
1. fix bug to avoid ”float division by zero”
> add centrality function and modify some detail

- easygraph/functions/community/LPA.py
Add SLPA and modify LPA
Add Example and Reference
> Add Example and Reference

- easygraph/functions/community/LPA.py
Solve the isolated node and infinite loop bug in LPA、SLPA、HANP、BMLPA 
And as verification, the code passes the following tests:
`   # G = eg.Graph()
G = eg.Graph()
D = nx.gn_graph(30)
D = D.to_undirected()
edges = list(D.edges)
for u, v in edges:
G.add_edge(u,v)
print(LPA(G))
print(SLPA(G,20,0.05))
print(HANP(G,0.1,0.05))
print(BMLPA(G,0.1)) `
> fix isolated node and infinite loop bug

- easygraph/functions/not_sorted/bridges.py
sometimes will get the error for the usage of set'{ }':
TypeError: 'set' object does not support indexing
> modify_syntax_of_all

- easygraph/functions/centrality/betweenness.py
- easygraph/functions/centrality/clossness.py
- easygraph/functions/community/LPA.py
- easygraph/functions/not_sorted/laplacian.py
- easygraph/functions/structural_holes/evaluation.py
- easygraph/utils/__init__.py
- easygraph/utils/misc.py
- setup.py
fix_parallel_for_memoryleak
fix_LPA_bug
> feat: parallel_complement

- easygraph/functions/structural_holes/HIS.py
- easygraph/functions/structural_holes/MaxD.py
Change `[frozenset]` to `list[frozenset]` in type annotations.
> Fix type annotation in MaxD.py

- .github/workflows/dummy_test.yaml
- .github/workflows/release.yaml
- .gitignore
- setup.py
Merge this branch to master to trigger a test upload to PyPI.
`release.yaml` will build sdist and wheel on `ubuntu-latest` on python 3.6 to 3.9, build scripts in `scripts/` are not used.
`PYPI_API_TOKEN` repo secret is needed to test this workflow, see #49.
> CI for auto release

- .github/workflows/release.yaml
Runs on both macOS and Ubuntu in CI.
> Runs on both macOS and Ubuntu in CI.

- scripts/build_easygraph_linux.sh
- scripts/build_easygraph_macos.sh
- scripts/build_packages_linux.sh
Following shellcheck's best practices.
> Shellcheck and fix 3 build scripts

- .github/workflows/release-cibuildwheel.yaml
- .github/workflows/test.yaml
- tox-conda-test.ini
- tox-conda.ini
- tox-test.ini
- tox.ini
> Make test CI work

- .github/workflows/test.yaml
- easygraph/classes/directed_graph.py
- easygraph/classes/directed_multigraph.py
- easygraph/classes/graph.py
- easygraph/classes/multigraph.py
- easygraph/readwrite/__init__.py
- easygraph/readwrite/pajek.py
- easygraph/readwrite/tests/test_pajek.py
Help needed: verify that the behavior of `pajek.py` is expected when working with the 4 Graph classes.
> Pajek support

- README.rst
> misc: add a general example

- .github/workflows/test.yaml
- MANIFEST.in
- cpp_easygraph/functions/components/biconnected.h
- setup.py
> fix "throw" on linux & give proper test.yaml

- easygraph/classes/directed_multigraph.py
- easygraph/classes/multigraph.py
- easygraph/functions/centrality/tests/test_betweenness.py
- easygraph/functions/centrality/tests/test_clossness.py
- easygraph/functions/centrality/tests/test_flowbetweenness.py
- easygraph/functions/community/LPA.py
- easygraph/functions/community/tests/test_ modularity_max_detection.py
- easygraph/functions/community/tests/test_LPA.py
- easygraph/functions/community/tests/test_modularity.py
- easygraph/functions/components/tests/test_biconnected.py
- easygraph/functions/drawing/tests/test_positioning.py
- easygraph/functions/not_sorted/tests/test_mst.py
- easygraph/functions/structural_holes/__init__.py
- easygraph/functions/structural_holes/tests/test_AP_Greedy.py
- easygraph/functions/structural_holes/tests/test_HAM.py
- easygraph/functions/structural_holes/tests/test_HIS.py
- easygraph/functions/structural_holes/tests/test_ICC.py
- easygraph/functions/structural_holes/tests/test_NOBE.py
- easygraph/functions/structural_holes/tests/test_evaluation.py
- easygraph/functions/structural_holes/tests/test_strong_connected_component.py
- easygraph/functions/structural_holes/tests/test_weakTie.py
- easygraph/readwrite/tests/test_edgelist.py
- easygraph/readwrite/tests/test_pickle.py
- easygraph/utils/convert_to_matrix.py
- easygraph/utils/tests/test_convert_to_matrix.py
- easygraph/utils/tests/test_mapped_queue.py
Adding unit tests to increase overall code coverge from 40.5% to 60.9%.
> adding unit tests

- cpp_easygraph/classes/__init__.h
- cpp_easygraph/classes/operation.cpp
- cpp_easygraph/classes/operation.h
- cpp_easygraph/cpp_easygraph.cpp
- easygraph/classes/operation.py
> feat:density

- easygraph/functions/not_sorted/bridges.py
Resolves: #issue-number-here
fixed:bridges.py
> fixed:bridges.py

- cpp_easygraph/cpp_easygraph.cpp
- cpp_easygraph/functions/__init__.h
- cpp_easygraph/functions/pagerank/__init__.h
- cpp_easygraph/functions/pagerank/pagerank.cpp
- cpp_easygraph/functions/pagerank/pagerank.h
> Added pagerank

- cpp_easygraph/common/utils.cpp
- cpp_easygraph/functions/cores/k_cores.cpp
- cpp_easygraph/functions/path/path.cpp
- easygraph/functions/centrality/pagerank.py
- easygraph/functions/components/connected.py
- easygraph/functions/path/path.py
feat: add hybrid for pagerank、spfa、cc
Resolves: #issue-number-here
> feat: add hybrid for pagerank、spfa、cc

- cpp_easygraph/classes/linkgraph.h
- cpp_easygraph/classes/segment_tree.cpp
- cpp_easygraph/common/common.h
- cpp_easygraph/common/utils.cpp
- cpp_easygraph/functions/centrality/betweenness.cpp
- cpp_easygraph/functions/centrality/closeness.cpp
- cpp_easygraph/functions/components/connected.cpp
- cpp_easygraph/functions/components/connected.h
- cpp_easygraph/functions/pagerank/pagerank.cpp
- cpp_easygraph/functions/path/path.cpp
- setup.py
fixed functions including closeness_centrality、betweenness_centrality、dijkstra;
Resolves: #issue-number-here
> fixed: replace pbds with segement_tree

- .github/workflows/pip-pybind11.yaml
- .gitmodules
- easygraph/functions/centrality/closeness.py
- easygraph/utils/decorators.py
- gpu_easygraph/CMakeLists.txt
- gpu_easygraph/common/common.h
- gpu_easygraph/common/utils.cpp
- gpu_easygraph/common/utils.h
- gpu_easygraph/functions/centrality/centrality.cpp
- gpu_easygraph/functions/centrality/centrality.h
- gpu_easygraph/functions/centrality/closeness_centrality.cu
- gpu_easygraph/functions/centrality/closeness_centrality.cuh
- gpu_easygraph/gpu_easygraph.cpp
- setup.py
> add GPU support. GPU ver closeness centrality is added

- gpu_easygraph/common/common.h
- gpu_easygraph/common/utils.cpp
- gpu_easygraph/common/utils.h
- gpu_easygraph/functions/centrality/closeness_centrality.cu
> optimize the usage of gpu memory

- setup.py
> Bug fixing: poor compatibility on windows after upgrading to Ver. 1.4

- README.md
> update README.md about GPU-related installation

- cpp_easygraph/CMakeLists.txt
- gpu_easygraph/CMakeLists.txt
> enhance compatibility of linking static libraries

- gpu_easygraph/CMakeLists.txt
> Bug Fixing: unsuitable compile options which leads wrong results

- gpu_easygraph/common/common.h
- gpu_easygraph/functions/path/path.cpp
> modify the INF in the EasyGraph-GPU module
